services:
  storage:
    image: redis
  counter:
    build: ./counterApp
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  books:
    build: ./booksApp
    ports:
      - 80:3000
    environment:
      - PORT=3000